# -*- coding: utf-8 -*-
"""sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYFu3Cim4a21lA0GxhrNEqx-2gXN-Fbk
"""

from sklearn.linear_model import LinearRegression
LR=LinearRegression()

t=[[5],[7],[12],[16],[20]]
m=[40,120,180,210,240]
LR.fit(t,m)

LR.predict([[19]])