# -*- coding: utf-8 -*-
"""social_network_ads.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ArwKC6g76RHj7JgTJ3wexMRlpYqTTdQ7
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

ads=pd.read_csv('/content/advertising.csv')

ads.head(25)

ads.isnull().sum()

ads.info()

ind=ads[['Age','Male','Area Income']]
dep=ads['Clicked on Ad']

LgR=LogisticRegression()

LgR.fit(ind,dep)

LgR.predict([[27,0,70000]])

age=int(input('Enter your age:'))
m=int(input('Enter 0 for female and 1 for male:'))
ai=float(input('Enter you salary:'))

from sklearn.metrics import accuracy_score

pval=LgR.predict(ind)
accuracy_score(dep,pval)